# Generated by Django 6.0.2 on 2026-02-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0002_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='last_practiced',
            field=models.DateField(auto_now=True),
        ),
    ]
