# Generated by Django 6.0.2 on 2026-02-22 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0003_skill_last_practiced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='last_practiced',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
